package com.flowcraft.api.workflow;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.ObjectNode; import java.util.*; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/workflows") public class WorkflowController { private final WorkflowRepository repo; private final ObjectMapper json; private final WorkflowExecutionService executions; public WorkflowController(WorkflowRepository repo,ObjectMapper json,WorkflowExecutionService executions){this.repo=repo;this.json=json;this.executions=executions;} private UUID user(String id){return UUID.fromString(id);} private JsonNode view(WorkflowEntity e){try{return json.readTree(e.getGraph());}catch(Exception x){throw new IllegalStateException(x);}} private String name(JsonNode node){if(!node.hasNonNull("name")||node.get("name").asText().isBlank())throw new IllegalArgumentException("Workflow name is required");return node.get("name").asText();}
 @GetMapping List<JsonNode> list(@AuthenticationPrincipal String id){return repo.findByOwnerIdOrderByUpdatedAtDesc(user(id)).stream().map(this::view).toList();}
 @GetMapping("/{id}") JsonNode get(@AuthenticationPrincipal String user,@PathVariable UUID id){return view(repo.findByIdAndOwnerId(id,user(user)).orElseThrow(()->new NoSuchElementException("Workflow not found")));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) JsonNode create(@AuthenticationPrincipal String user,@RequestBody JsonNode body)throws Exception{ObjectNode doc=(ObjectNode)body.deepCopy();UUID id=UUID.randomUUID();doc.put("id",id.toString());doc.put("updatedAt","Just now");if(!doc.has("nodes"))doc.putArray("nodes");if(!doc.has("edges"))doc.putArray("edges");if(!doc.has("runs"))doc.putArray("runs");repo.save(new WorkflowEntity(id,user(user),name(doc),json.writeValueAsString(doc)));return doc;}
 @PutMapping("/{id}") JsonNode update(@AuthenticationPrincipal String user,@PathVariable UUID id,@RequestBody JsonNode body)throws Exception{WorkflowEntity e=repo.findByIdAndOwnerId(id,user(user)).orElseThrow(()->new NoSuchElementException("Workflow not found"));ObjectNode doc=(ObjectNode)body.deepCopy();doc.put("id",id.toString());e.update(name(doc),json.writeValueAsString(doc));repo.save(e);return doc;}
 @PostMapping("/{id}/validate") WorkflowExecutionService.Validation validate(@AuthenticationPrincipal String user,@PathVariable UUID id){return executions.validate((ObjectNode)get(user,id));}
 @PostMapping("/{id}/execute") WorkflowExecutionService.Execution execute(@AuthenticationPrincipal String user,@PathVariable UUID id)throws Exception{WorkflowEntity e=repo.findByIdAndOwnerId(id,user(user)).orElseThrow(()->new NoSuchElementException("Workflow not found"));ObjectNode graph=(ObjectNode)view(e);WorkflowExecutionService.Execution execution=executions.run(user(user),graph);e.update(name(graph),json.writeValueAsString(graph));repo.save(e);return execution;}
 @GetMapping("/{id}/executions") JsonNode history(@AuthenticationPrincipal String user,@PathVariable UUID id){return get(user,id).path("runs");}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@AuthenticationPrincipal String user,@PathVariable UUID id){repo.findByIdAndOwnerId(id,user(user)).ifPresent(repo::delete);}
}
